language: rust
sudo: false
rust: nightly
env:
  matrix:
    - TRIPLE= ARCH=amd64
    - TRIPLE= ARCH=x86
script:
  - make -C Kernel/ UPDATE
  - make -C Kernel/ ../libcore/lib.rs
  - make -C Kernel/ all
