language: rust
sudo: false
rust: nightly
env:
  global:
    - TRIPLE=
  matrix:
    - ARCH=amd64
    - ARCH=x86
script:
  - make -C Kernel/ UPDATE
  - make -C Kernel/ ../libcore/lib.rs
  - make -C Kernel/ all
